server:
  port: 8443
  ssl:
    key-store-password: zaq12wsx
    key-store: src/main/resources/mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  h2:
    console:
      path: /h2-console
      enabled:  true
logging:
  level:
    root:
      DEBUG


